version: '3.8'

services:
  web3-discord-bot:
    build: .
    container_name: web3-discord-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - config.env
    user: "1001:1001"
    volumes:
      - bot-logs:/usr/src/app/logs
    networks:
      - bot-network
    # healthcheck:
    #   test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

networks:
  bot-network:
    driver: bridge

volumes:
  bot-logs: 